version: '3.7'

services:
  php:
    env_file: .env
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: intus-php:latest
    container_name: 'php'
    environment:
      PHP_IDE_CONFIG: 'serverName=docker'
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: '/var/www/html'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: 'php'
    networks:
      frontend:
      backend:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: intus-nginx:latest
    container_name: 'nginx'
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - '80:80'
      - '443:443'
    hostname: 'nginx'
    networks:
      frontend:
    restart: unless-stopped

  mysql:
    env_file: .env
    image: mysql:latest
    container_name: 'mysql'
    volumes:
      - mysql_volume:/var/lib/postgresql/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
    restart: unless-stopped
    hostname: 'mysql'
    networks:
      backend:
        ipv4_address: 172.20.0.101

networks:
  frontend:
    driver: bridge
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  mysql_volume:
